[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hw_1"
version = "1.0.0"
description = "hw 1 tasks 1-3"
requires-python = ">=3.8"
dependencies = []